# Generated by Django 5.0.3 on 2024-03-30 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_transaction_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='owe_user',
        ),
        migrations.CreateModel(
            name='owee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transection_owee', to='myapp.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
