# Generated by Django 5.0.3 on 2024-03-30 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_transaction_owe_user_owee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='owee',
            name='transection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_owee', to='myapp.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
