# Generated by Django 5.0.3 on 2024-03-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_owee_transection_alter_transaction_paid_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owee',
            old_name='transection',
            new_name='transaction',
        ),
    ]
