# Generated by Django 5.0.3 on 2024-03-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='distribute',
            field=models.IntegerField(choices=[(1, 'equal'), (2, 'exact'), (1, 'percent')], default=1),
        ),
    ]
